Write-Host "Facility Intelligence Copilot demo"
Write-Host "1. Start infrastructure"
Write-Host "   docker compose up -d postgres kafka"
Write-Host "2. Start backend"
Write-Host "   cd backend; python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
Write-Host "3. Start frontend"
Write-Host "   cd frontend; npm install; npm run dev -- --host 0.0.0.0"
Write-Host "4. Start simulator"
Write-Host "   cd simulator; python simulator.py --scenario airflow_restriction --interval 5"
Write-Host "5. Open frontend and select HVAC-007"
Write-Host "6. Watch telemetry, health decline, anomaly, and alert creation"
Write-Host "Docker is unavailable in this environment; these commands are documented for live execution on a host with Docker installed."
