Write-Host "=== FACILITY INTELLIGENCE COPILOT: AIRFLOW RESTRICTION DEMO ==="
Write-Host ""
Write-Host "[1/7] Start backend"
Write-Host "   cd facility-intelligence-copilot/backend; python -m uvicorn main:app --host 0.0.0.0 --port 8000"
Write-Host ""
Write-Host "[2/7] Start frontend"
Write-Host "   cd facility-intelligence-copilot/frontend; npm install; npm run dev -- --host 0.0.0.0 --port 5173"
Write-Host ""
Write-Host "[3/7] Start simulator"
Write-Host "   cd facility-intelligence-copilot/simulator; python simulator.py --scenario airflow_restriction --interval 5"
Write-Host ""
Write-Host "[4/7] Observe HVACT-007 telemetry and digital twin health"
Write-Host "   Metric pattern: Airflow down, Temperature up, Pressure up, Energy up, Health down"
Write-Host ""
Write-Host "[5/7] Alert appears"
Write-Host "   AIRFLOW_RESTRICTION WARNING"
Write-Host ""
Write-Host "[6/7] Run Facility X-Ray"
Write-Host "   Investigate asset 7 with alert 101"
Write-Host ""
Write-Host "[7/7] Review evidence and recommendation"
Write-Host "   Root cause: airflow restriction"
Write-Host "   Recommendation: inspect filter, damper, and airflow path"
Write-Host ""
Write-Host "Demo is ready when the backend, frontend, and simulator are running in a local environment."
