from __future__ import annotations

from typing import Dict, List, Optional, Any
from backend.counterfactual.schemas import CandidatePlan
from backend.ml.features.feature_schema import FaultClass


class CandidateGenerator:
    """
    Synthesizes diverse intervention candidates for counterfactual validation.
    Integrates SNS Cognitive Agent proposals with automated thermodynamic baselines.
    """

    @classmethod
    def generate_candidates(
        cls,
        fault_class: str,
        current_telemetry: Dict[str, float],
        sns_proposed_plan: Optional[Dict[str, Any]] = None,
    ) -> List[CandidatePlan]:
        candidates: List[CandidatePlan] = []
        
        cur_oad = current_telemetry.get("oa_dmpr", 25.0)
        cur_chwc = current_telemetry.get("chwc_vlv", 35.0)
        cur_sf = current_telemetry.get("sf_spd", 70.0)

        # 1. Ingest SNS Proposed Candidate if present
        if sns_proposed_plan and "interventions" in sns_proposed_plan:
            candidates.append(
                CandidatePlan(
                    candidate_id="cand_sns_agent_01",
                    title=sns_proposed_plan.get("title", "SNS Copilot Multi-Agent Action Plan"),
                    description=sns_proposed_plan.get("description", "Intervention generated by SNS multi-agent facility copilot."),
                    proposed_by="SNS_COGNITIVE_AGENT",
                    interventions=sns_proposed_plan["interventions"],
                    expected_rationale=sns_proposed_plan.get("rationale", "Cognitive reasoning from facility knowledge base."),
                )
            )

        # 2. Domain-specific candidate generation based on diagnosed root cause
        if fault_class == FaultClass.DAMPER_STUCK.value:
            candidates.extend([
                CandidatePlan(
                    candidate_id="cand_economizer_lock_01",
                    title="Lock Economizer to Min Position (15%) + VFD Trim",
                    description="Force outdoor damper to 15% minimum ventilation, recalibrate chilled water valve to 42%, and trim fan speed.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"oa_dmpr": 15.0, "chwc_vlv": 42.0, "sf_spd": 72.0},
                    expected_rationale="Eliminates outdoor thermal air ingestion while satisfying ASHRAE 62.1 indoor ventilation rates.",
                ),
                CandidatePlan(
                    candidate_id="cand_aggressive_cooling_02",
                    title="Full Chilled Water Valve Override (100%)",
                    description="Open chilled water valve to 100% without locking outdoor air damper.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"oa_dmpr": cur_oad, "chwc_vlv": 100.0, "sf_spd": 85.0},
                    expected_rationale="Attempt to overcome heat load by max cooling coil actuation.",
                ),
                CandidatePlan(
                    candidate_id="cand_out_of_bounds_test",
                    title="High-Pressure Damper Purge Override (120%)",
                    description="Force actuator beyond 100% mechanical stroke to unbind sticky linkage.",
                    proposed_by="OPERATOR_OVERRIDE",
                    interventions={"oa_dmpr": 120.0, "chwc_vlv": 50.0, "sf_spd": 90.0},
                    expected_rationale="High torque stroke test.",
                ),
            ])
        elif fault_class == FaultClass.COIL_FOULING_OR_LEAKAGE.value:
            candidates.extend([
                CandidatePlan(
                    candidate_id="cand_coil_modulation_01",
                    title="Optimized Heat Exchange Modulation + 15% Fan Speed Boost",
                    description="Modulate cooling valve to 65% optimum heat transfer point and increase airflow to 82% to restore sensible heat exchange.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"chwc_vlv": 65.0, "sf_spd": 82.0, "oa_dmpr": 18.0},
                    expected_rationale="Prevents laminar coil bypass and restores required thermal heat flux.",
                ),
                CandidatePlan(
                    candidate_id="cand_coil_saturation_02",
                    title="Saturate Valve (100%) at Reduced Airflow (50%)",
                    description="Open valve completely while cutting airflow.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"chwc_vlv": 100.0, "sf_spd": 50.0, "oa_dmpr": 20.0},
                    expected_rationale="Test coil heat saturation at lower mass flow.",
                ),
            ])
        elif fault_class == FaultClass.STATIC_PRESSURE_SURGE.value:
            candidates.extend([
                CandidatePlan(
                    candidate_id="cand_sp_relief_01",
                    title="Acoustic Static Pressure Relief: VFD Fan Trim to 58%",
                    description="Step down supply fan speed from 85% to 58% to immediately drop duct static pressure below 2.0 in.w.g.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"sf_spd": 58.0, "oa_dmpr": 20.0, "chwc_vlv": 45.0},
                    expected_rationale="Prevents duct joint separation while maintaining temperature control.",
                ),
                CandidatePlan(
                    candidate_id="cand_sp_hazard_02",
                    title="Full Boost VFD Fan Speed (95%)",
                    description="Increase fan speed to force air through restricted duct zones.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"sf_spd": 95.0, "oa_dmpr": 25.0, "chwc_vlv": 50.0},
                    expected_rationale="High pressure purge.",
                ),
            ])
        elif fault_class == FaultClass.FAN_BELT_SLIP.value:
            candidates.extend([
                CandidatePlan(
                    candidate_id="cand_belt_slip_comp_01",
                    title="VFD Slip Speed Compensation (86%) with Reset Damper",
                    description="Compensate for belt friction slip by adjusting VFD output frequency until design airflow (2600 CFM) is met.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"sf_spd": 86.0, "oa_dmpr": 22.0, "chwc_vlv": 40.0},
                    expected_rationale="Restores target ventilation rate without thermal overshoot.",
                ),
                CandidatePlan(
                    candidate_id="cand_belt_overdrive_02",
                    title="Fan Motor Overdrive (110%)",
                    description="Drive VFD past rated speed ceiling.",
                    proposed_by="OPERATOR_OVERRIDE",
                    interventions={"sf_spd": 110.0, "oa_dmpr": 20.0, "chwc_vlv": 45.0},
                    expected_rationale="Emergency airflow recovery.",
                ),
            ])
        else:
            # Baseline Nominal Energy Optimization Candidates
            candidates.extend([
                CandidatePlan(
                    candidate_id="cand_energy_tune_01",
                    title="Adaptive Energy Baseline Reset (ASHRAE 90.1 Trim)",
                    description="Trim fan speed by 8% and optimize outdoor air damper to 20% free cooling.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"sf_spd": max(45.0, cur_sf - 8.0), "oa_dmpr": 20.0, "chwc_vlv": max(20.0, cur_chwc - 5.0)},
                    expected_rationale="Harvests 12-18% electrical energy savings while holding zone comfort band.",
                ),
                CandidatePlan(
                    candidate_id="cand_eco_trim_02",
                    title="Deep Setback Eco Mode",
                    description="Setback supply fan to minimum 35% speed during low-occupancy transitions.",
                    proposed_by="GSENSE_ANALYTICAL_ENGINE",
                    interventions={"sf_spd": 35.0, "oa_dmpr": 10.0, "chwc_vlv": 20.0},
                    expected_rationale="Maximum energy conservation profile.",
                ),
            ])

        return candidates
